-- ==============================================================================
-- CRIAÇÃO DA TABELA: public.plat_movimentos (Histórico de Movimentos de Stock)
-- ==============================================================================
-- Campos baseados no ficheiro CSV de movimentos com suporte multi-cliente
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.plat_movimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Campos de identificação de cliente
    cliente_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
    sigla_cliente TEXT,
    
    -- Campos importados do CSV de movimentos
    num_linha INTEGER,
    data DATE,
    documento TEXT,
    chave1 TEXT,
    chave2 TEXT,
    ativa BOOLEAN DEFAULT TRUE,
    valor_unitario NUMERIC(15, 4) DEFAULT 0,
    valor_adicional NUMERIC(15, 4) DEFAULT 0,
    valor_abater NUMERIC(15, 4) DEFAULT 0,
    artigo TEXT,
    descricao TEXT,
    tipo_artigo TEXT,
    armazem TEXT,
    localizacao TEXT,
    lote TEXT,
    validade DATE,
    datafabrico DATE,
    tipo_movimento TEXT,
    quantidade NUMERIC DEFAULT 0,
    familia TEXT,
    sub_familia TEXT,
    
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Restrições
    CONSTRAINT plat_movimentos_documento_num_linha_key UNIQUE (documento, num_linha)
);

-- Índices para otimização de consultas
CREATE INDEX IF NOT EXISTS idx_plat_movimentos_artigo ON public.plat_movimentos(artigo);
CREATE INDEX IF NOT EXISTS idx_plat_movimentos_armazem ON public.plat_movimentos(armazem);
CREATE INDEX IF NOT EXISTS idx_plat_movimentos_lote ON public.plat_movimentos(lote);
CREATE INDEX IF NOT EXISTS idx_plat_movimentos_data ON public.plat_movimentos(data);
CREATE INDEX IF NOT EXISTS idx_plat_movimentos_documento ON public.plat_movimentos(documento);
CREATE INDEX IF NOT EXISTS idx_plat_movimentos_cliente_id ON public.plat_movimentos(cliente_id);

-- Ativação de RLS (Row Level Security)
ALTER TABLE public.plat_movimentos ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'plat_movimentos' AND policyname = 'Acesso total a plat_movimentos para autenticados'
  ) THEN
    CREATE POLICY "Acesso total a plat_movimentos para autenticados"
    ON public.plat_movimentos
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'plat_movimentos' AND policyname = 'Acesso total a plat_movimentos para anon'
  ) THEN
    CREATE POLICY "Acesso total a plat_movimentos para anon"
    ON public.plat_movimentos
    FOR ALL
    TO anon
    USING (true)
    WITH CHECK (true);
  END IF;
END
$$;
