-- Tabela criada a partir do ficheiro Saidas_Plat.txt (exportação de Saídas / Vendas do Primavera)
CREATE TABLE IF NOT EXISTS public.plat_saidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    data TIMESTAMP,
    entidade TEXT,
    tipo_doc TEXT,
    num_doc INTEGER,
    total_merc NUMERIC(15, 3),
    total_iva NUMERIC(15, 3),
    total_desc NUMERIC(15, 3),
    total_outros NUMERIC(15, 3),
    serie TEXT,
    morada TEXT,
    nome TEXT,
    localidade TEXT,
    cod_postal TEXT,
    cod_postal_localidade TEXT,
    entidade_entrega TEXT,
    morada_entrega TEXT,
    nome_entrega TEXT,
    localidade_entrega TEXT,
    cod_postal_entrega TEXT,
    cod_postal_localidade_entrega TEXT,
    num_linha INTEGER,
    artigo TEXT,
    desconto1 NUMERIC(10, 2),
    desconto2 NUMERIC(10, 2),
    desconto3 NUMERIC(10, 2),
    taxa_iva NUMERIC(10, 2),
    quantidade NUMERIC(15, 3),
    cod_iva TEXT,
    prec_unit NUMERIC(15, 3),
    armazem TEXT,
    desconto_comercial NUMERIC(15, 3),
    lote TEXT,
    descricao TEXT,
    devolucao BOOLEAN DEFAULT FALSE,
    total_da NUMERIC(15, 3),
    total_dc NUMERIC(15, 3),
    total_iliquido NUMERIC(15, 3),
    total_df NUMERIC(15, 3),
    total_recargo NUMERIC(15, 3),
    total_iva_linhas NUMERIC(15, 3),
    id_linha TEXT,
    id_cabec_doc TEXT,
    familia TEXT,
    subfamilia TEXT,
    pcm NUMERIC(15, 3),
    desc_pag NUMERIC(10, 2),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativação de RLS
ALTER TABLE public.plat_saidas ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS
CREATE POLICY "plat_saidas_select_policy" ON public.plat_saidas FOR SELECT TO authenticated USING (true);
CREATE POLICY "plat_saidas_insert_policy" ON public.plat_saidas FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "plat_saidas_update_policy" ON public.plat_saidas FOR UPDATE TO authenticated USING (true);
CREATE POLICY "plat_saidas_delete_policy" ON public.plat_saidas FOR DELETE TO authenticated USING (true);
CREATE POLICY "plat_saidas_anon_all" ON public.plat_saidas FOR ALL TO anon USING (true) WITH CHECK (true);

-- Índices de performance
CREATE INDEX IF NOT EXISTS idx_plat_saidas_artigo ON public.plat_saidas (artigo);
CREATE INDEX IF NOT EXISTS idx_plat_saidas_lote ON public.plat_saidas (lote);
CREATE INDEX IF NOT EXISTS idx_plat_saidas_data ON public.plat_saidas (data);
CREATE INDEX IF NOT EXISTS idx_plat_saidas_doc ON public.plat_saidas (tipo_doc, serie, num_doc);
