-- Create table for imported documents based on the provided CSV format
CREATE TABLE IF NOT EXISTS public.doc_venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Client identification fields added at the beginning
    cliente_id UUID REFERENCES public.clients(id),
    sigla_cliente TEXT,
    
    -- Fields from CSV
    data DATE,
    serie TEXT,
    entidade TEXT,
    tipo_doc TEXT,
    num_doc INTEGER,
    requisicao TEXT,
    num_contribuinte TEXT,
    nome TEXT,
    morada TEXT,
    localidade TEXT,
    cod_postal TEXT,
    cod_postal_localidade TEXT,
    total_merc NUMERIC,
    desc_pag NUMERIC,
    total_iva NUMERIC,
    total_desc NUMERIC,
    total_outros NUMERIC,
    num_linha INTEGER,
    artigo TEXT,
    taxa_iva NUMERIC,
    desconto1 NUMERIC,
    desconto2 NUMERIC,
    desconto3 NUMERIC,
    quantidade NUMERIC,
    cod_iva TEXT,
    armazem TEXT,
    lote TEXT,
    preco_liquido NUMERIC,
    descricao TEXT,
    devolucao BOOLEAN,
    total_da NUMERIC,
    total_dc NUMERIC,
    total_iliquido NUMERIC,
    total_df NUMERIC,
    total_iva_art NUMERIC,
    pc_medio NUMERIC,
    pc_ultimo NUMERIC,
    pc_padrao NUMERIC,
    
    -- Audit fields (optional but recommended)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: The `devolucao` field is defined as BOOLEAN. 
-- In PostgreSQL, when importing data, '0' will automatically be cast to FALSE and '1' to TRUE.
-- If the CSV contains 'FALSO'/'VERDADEIRO' string literals instead of 0/1, 
-- you may need to map them to false/true during the import process or use a temporary TEXT column to cast them afterwards.

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

ALTER TABLE public.doc_venda ENABLE ROW LEVEL SECURITY;

CREATE POLICY "doc_venda_select_policy" ON public.doc_venda FOR SELECT TO authenticated
USING (
    (( SELECT users.role FROM users WHERE users.id = auth.uid() ) = ANY (ARRAY['admin'::text, 'gestor'::text])) 
    OR 
    (cliente_id = ( SELECT users.client_id FROM users WHERE users.id = auth.uid() ))
);

CREATE POLICY "doc_venda_insert_policy" ON public.doc_venda FOR INSERT TO authenticated
WITH CHECK (
    (( SELECT users.role FROM users WHERE users.id = auth.uid() ) = ANY (ARRAY['admin'::text, 'gestor'::text])) 
    OR 
    (cliente_id = ( SELECT users.client_id FROM users WHERE users.id = auth.uid() ))
);

CREATE POLICY "doc_venda_update_policy" ON public.doc_venda FOR UPDATE TO authenticated
USING (
    (( SELECT users.role FROM users WHERE users.id = auth.uid() ) = ANY (ARRAY['admin'::text, 'gestor'::text])) 
    OR 
    (cliente_id = ( SELECT users.client_id FROM users WHERE users.id = auth.uid() ))
);

CREATE POLICY "doc_venda_delete_policy" ON public.doc_venda FOR DELETE TO authenticated
USING (
    (( SELECT users.role FROM users WHERE users.id = auth.uid() ) = ANY (ARRAY['admin'::text, 'gestor'::text]))
);
