-- Tabela criada a partir do ficheiro Entradas_Plat.txt (exportação de Entradas / Compras do Primavera)
CREATE TABLE IF NOT EXISTS public.entradas_plat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    serie TEXT,
    tipo_doc TEXT,
    num_doc INTEGER,
    entidade TEXT,
    data TIMESTAMP,
    num_doc_externo TEXT,
    total_merc NUMERIC(15, 3),
    total_iva NUMERIC(15, 3),
    total_desc NUMERIC(15, 3),
    total_outros NUMERIC(15, 3),
    requisicao TEXT,
    num_contribuinte TEXT,
    localidade TEXT,
    morada TEXT,
    nome TEXT,
    cod_postal TEXT,
    cod_postal_localidade TEXT,
    id_linha TEXT,
    id_cabec_compras TEXT,
    referencia TEXT,
    num_linha INTEGER,
    desconto1 NUMERIC(10, 2),
    desconto2 NUMERIC(10, 2),
    desconto3 NUMERIC(10, 2),
    taxa_iva NUMERIC(10, 2),
    quantidade NUMERIC(15, 3),
    cod_iva TEXT,
    prec_unit NUMERIC(15, 3),
    armazem TEXT,
    lote TEXT,
    descricao TEXT,
    total_iliquido NUMERIC(15, 3),
    total_da NUMERIC(15, 3),
    total_dc NUMERIC(15, 3),
    total_df NUMERIC(15, 3),
    total_recargo NUMERIC(15, 3),
    total_iva_linhas NUMERIC(15, 3),
    familia TEXT,
    subfamilia TEXT,
    entidade_entrega TEXT,
    nome_entrega TEXT,
    localidade_entrega TEXT,
    morada_entrega TEXT,
    cod_postal_entrega TEXT,
    cod_postal_localidade_entrega TEXT,
    artigo TEXT,
    desc_pag NUMERIC(10, 2),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativação de RLS
ALTER TABLE public.entradas_plat ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS
CREATE POLICY "entradas_plat_select_policy" ON public.entradas_plat FOR SELECT TO authenticated USING (true);
CREATE POLICY "entradas_plat_insert_policy" ON public.entradas_plat FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "entradas_plat_update_policy" ON public.entradas_plat FOR UPDATE TO authenticated USING (true);
CREATE POLICY "entradas_plat_delete_policy" ON public.entradas_plat FOR DELETE TO authenticated USING (true);
CREATE POLICY "entradas_plat_anon_all" ON public.entradas_plat FOR ALL TO anon USING (true) WITH CHECK (true);

-- Índices de performance
CREATE INDEX IF NOT EXISTS idx_entradas_plat_artigo ON public.entradas_plat (artigo);
CREATE INDEX IF NOT EXISTS idx_entradas_plat_lote ON public.entradas_plat (lote);
CREATE INDEX IF NOT EXISTS idx_entradas_plat_data ON public.entradas_plat (data);
CREATE INDEX IF NOT EXISTS idx_entradas_plat_doc ON public.entradas_plat (tipo_doc, serie, num_doc);
CREATE INDEX IF NOT EXISTS idx_entradas_plat_armazem ON public.entradas_plat (armazem);
